### ISSUE TITLE
Chatterino submodule link returns 404 error

### ISSUE THREAD

**Issue by bogsnarth** [JohnCiubuc/StreamLinkerino#1]
hi, sorry to bother you, from the activity on the project it seems like something mostly for your own personal use. fully understand if you don't want to make changes or update it. i am a relative noob to using git and only have a little bit of scripting/coding experience, so i apologize if this is not the way i should try fix this problem.

**issue**: when trying to clone the project, the link to the chatterino submodule reaches a 404, because it apparently points to a specific commit that no longer exists. it needs to be changed to point to the current stable branch.

i tried forking the project to fix the problem myself, but as i said, i'm new to git and not very familiar with coding in general. i was unable to edit the modules to point to the correct resource in my fork, so i don't know what i need to do to be able to do that.

thanks for making the project, and i appreciate any help you can offer.

**Comment by JohnCiubuc** [comment]
Based alazymeme to stick dependabot to fix it. 

This is a personal project and honestly my first time messing with submodules haha. You just need to apply the patch on chatterino prior to building to enable cross-communication between the streamlinkerino client and chatterino. So if submodules are still screwed up, might as well go the dumb-but-true way of cloning chatterino separately and apply the patch on it there
