### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by D3XX3R** [JohnCiubuc/StreamLinkerino#22]
Hey is there any chance you could upload a pre-compiled release?
I can't compile it.

**Comment by dewcked** [comment]
This project doesn't seem to be actively maintained but if someone is looking for the way to build this without any problem, I found a [simple docker image](https://github.com/OlivierLDff/QtLinuxCMakeDocker) fit to this project.

0. Install docker and git
1. git clone https://github.com/JohnCiubuc/streamlinkerino.git --recurse-submodules
2. cd streamlinkerino
3. Pull docker image from there.
3-1. Linux) docker run -it --rm -v $(pwd):/src/ --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined reivilo1234/qt-linux-cmake:qt5.15.1 bash
3-2. Windows) docker run -it --rm -v %CD%:/src/ --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined reivilo1234/qt-linux-cmake:qt5.15.1 bash
4. mkdir build && cd build
5. cmake ../src && make

Now everything works like a charm!

**Comment by D3XX3R** [comment]
It indeed works like a charm. Thank you very much!
