### ISSUE TITLE
Need to link latest streamlink submodule due to Twitch API replacement.

### ISSUE THREAD

**Issue by dewcked** [JohnCiubuc/StreamLinkerino#73]
> Thank you for this project :heart:

Project could be broken due to streamlink API replacement resulted by twitch API replacement.

[This pull request from streamlink](https://github.com/streamlink/streamlink/pull/3929) adapted Twitch's GraphQL API. To say simple, Helix, new Twitch's official API that replaces Kraken, forces devs to send user's auth token to use it. So streamlink replaced that API to Twitch's GraphQL API.

I checked latest [streamlink-twitch-gui release](https://github.com/streamlink/streamlink-twitch-gui/releases) now uses Helix API (need users login to Twitch), so this project is still one possible alternative to it for whom doesn't want to login. (I don't know if the streamlink-twitch-gui dev will add option for GraphQL).

Fast workaround should be `git submodule update --recursive --remote`([from StackOverflow](https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules)) before [building steps](https://github.com/JohnCiubuc/StreamLinkerino/issues/22#issuecomment-1030503457).  I checked build is successful with latest streamlink.

If you add guide in README for updating submodules I would appreciate.

**Comment by JohnCiubuc** [comment]
Thanks for the help with the docker image in the previous issue, I really appreciate it. I will update the README to include that information as well.

I don't know exactly how the project will fail to work with updated streamlink. Perhaps I'll add whatever config information streamlink needs if it isn't saved locally or what not. Will have to see. 

Many thanks for your contributions 💖. Helped get the project up and running again haha

**Comment by dewcked** [comment]
Wait... I thought this project was using streamlink in build process somewhere. If not, it should be ok with just updating README.
